loanpro.app:
  jwtExpirationMs: '9999999'
  jwtCookieName: loanpro
  jwtSecret: ======================loanpro=Spring===========================

spring:
  cloud.gcp:
    sql.instance-connection-name: loan-pro-calculator:us-central1:mysql-loanpro
    sql.database-name: loanpro
  datasource.username: root
  datasource.password: tutipapai@21
  datasource.hikari.maximum-pool-size: 10
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baselineOnMigrate: true
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

client.string:
  name: randomStringClient
  url: 'https://www.random.org'
  digits: 'on'
  upperalpha: 'on'
  loweralpha: 'on'
  unique: 'on'
  rnd: 'new'
  format: 'plain'

mdcfilter:
  request-id-header: X-Request-Id
  response-id-header: X-Request-Id
  mdc-log-key: MDCFilter.UUID
  mdc-log-user: MDCFilter.USER

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(-%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(: requestId:) %clr(%X{MDCFilter.UUID} :) %clr(userId:) %clr(%X{MDCFilter.USER} :){red} %m%n %wEx'

errors:
  expose-arguments: ALWAYS