loanpro.app:
  jwtExpirationMs: '9999999'
  jwtCookieName: loanpro
  jwtSecret: ======================loanpro=Spring===========================

spring:
  datasource:
    username: loan_pro
    url: jdbc:mysql://localhost:3306/loan_pro?useSSL=false
    password: 'loan_pro_path'
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baselineOnMigrate: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

client.string:
  name: randomStringClient
  url: 'https://www.random.org'
  digits: 'on'
  upperalpha: 'on'
  loweralpha: 'on'
  unique: 'on'
  rnd: 'new'
  format: 'plain'